image:
  dockerNamespace: zhenyanovikov/
  name: service2
  tag: 0.4

migrations:
  image:
    name: service1-migrations
    dockerNamespace: zhenyanovikov/
    tag: 0.1
  config:
    POSTGRESQL_URL: "postgres://demo:demo@postgres:5432/demo?sslmode=disable"
    VERSION: "20230522163550"

configs:
  POSTGRES_DB: demo
  POSTGRES_HOST: postgres

secrets:
  POSTGRES_USER: "ZGVtbw=="
  POSTGRES_PASSWORD: "ZGVtbw=="

service:
  ports:
    - name: http
      port: 80
      containerPort: 8080

ingress:
  path: /service2
  port: http