apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: service1-destination
spec:
  host: service1
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 2
      interval: 10s
      baseEjectionTime: 90s
      maxEjectionPercent: 80
